### ISSUE TITLE
Forwarded attributes (tango9)

### ISSUE THREAD

**Issue by tiagocoutinho** [tiagocoutinho/PyTango#10]
Implement forwarded attributes in PyTango 9

**Comment by jyotinpo** [comment]
Hi Tiago,

Tried using the Forwarded Attribute feature in PyTango 9.2.4. However, I am facing issue with it. Details are posted in the Forum post:

http://www.tango-controls.org/community/forum/c/development/python/forwarded-attributes-in-python/

Can you please look into this issue and guide further?

Regards,
Jyotin

**Comment by vxgmichel** [comment]
Hi @jyotinpo,

Could you create a new issue [here](https://github.com/tango-controls/pytango/issues/new)?

Thanks for the report!

**Comment by jyotinpo** [comment]
Hi @vxgmichel,

Thanks for replying.
Created new issue (https://github.com/tango-controls/pytango/issues/231) on GitHub for this problem.
